Resources:
  CognitoUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      MfaConfiguration: OFF
      AccountRecoverySetting:
        RecoveryMechanisms:
          - 
            Name: verified_email
            Priority: 1
      UserPoolName: fitnet-app-users-${self:custom.stage}
      AutoVerifiedAttributes: 
        - email
      Schema: 
        - 
          AttributeDataType: String
          Name: uid
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: False
          RequireNumbers: True
          RequireSymbols: False
          RequireUppercase: True

  CognitoUserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: fitnet-app-${self:custom.stage}
      GenerateSecret: true
      UserPoolId:
        Ref: CognitoUserPool

  ApiGatewayAuthorizer:
    DependsOn:
      - ApiGatewayRestApi
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: cognito-authorizer-${self:custom.stage}
      IdentitySource: method.request.header.authorization
      RestApiId:
        Ref: ApiGatewayRestApi
      Type: COGNITO_USER_POOLS
      ProviderARNs:
        - Fn::GetAtt: [CognitoUserPool, Arn] 