service: fitnet-serverless

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    APPUSER_TABLE: AppUsers
    WORKOUT_TABLE: Workouts
    WORKOUTINSTANCE_TABLE: WorkoutInstances
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:554065750062:table/*"

functions:
  - ${file(appUsers/serverless.functions.yml)}
  - ${file(workouts/serverless.functions.yml)}
  - ${file(workoutInstances/serverless.functions.yml)}

resources:
  - ${file(appUsers/serverless.resource.yml)}
  - ${file(workouts/serverless.resource.yml)}
  - ${file(workoutInstances/serverless.resource.yml)}

